source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'mysql2','~>0.3.11'
gem 'json','~>1.7.6'
gem 'i18n','~>0.6.1'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end
gem 'execjs','~>1.4.0'
gem 'jquery-rails','~>2.2.1'
#Easy deployment in Amazon EC2
gem 'capistrano','~>2.14.2'
gem 'rvm-capistrano','~>1.2.7'
#ActiveModels has_secure_password
gem "bcrypt-ruby", '~>3.0.1',:require => "bcrypt"
#Authentication Framework
gem 'authlogic','~>3.2.0'
#Paginations
gem 'will_paginate', '~> 3.0'
#Search Utility
gem 'meta_search','~>1.1.3'
gem 'sunspot_rails','~>2.0.0'
gem 'nokogiri','~>1.5.9'

group :development,:test do
  gem 'hirb','~>0.7.1'
  gem 'interactive_editor','~>0.0.10'
  gem 'sunspot_solr','~>2.0.0'
end
#Using Unicorn App server
gem 'unicorn','~>4.6.2'

gem 'net-ssh','~>2.6.7'
gem 'net-scp','~>1.1.0'
gem 'net-sftp','~>2.1.2'
gem 'net-ssh-gateway','~>1.2.0'
